In [1]:
import torch 

In [3]:
x = torch.rand(2,3)
x

tensor([[0.0043, 0.4154, 0.4813],
        [0.1677, 0.3457, 0.4853]])

In [5]:
#permutation
x_p = torch.einsum("ij->ji", x)
x_p.shape

torch.Size([3, 2])

In [6]:
#summation
x_s = torch.einsum("ij->", x)
x_s

tensor(1.8996)

In [11]:
#row sum
x_rs = torch.einsum("ij->i", x)
x_rs

tensor([0.9010, 0.9987])

In [12]:
#col sum
x_cs = torch.einsum("ij->j", x)
x_cs

tensor([0.1719, 0.7611, 0.9666])

In [14]:
# matrix vector multiplication
v = torch.rand(1, 3)
x_mv = torch.einsum("ij, kj->ik", x, v)
x_mv

tensor([[0.3184],
        [0.3024]])

In [15]:
# matrix matrix multiplication
x_mm = torch.einsum("ij, kj -> ik", x, x)
x_mm

tensor([[0.4042, 0.3779],
        [0.3779, 0.3832]])

In [16]:
# Dot product first row of a matrix
x_dp = torch.einsum("i,i->", x[0], x[0])
x_dp

tensor(0.4042)

In [29]:
# Dot product of matrix
x_dp = torch.einsum("ij, ij -> ", x, x)
x_dp

tensor(0.7874)

In [38]:
# dot product of a matrix
total = 0
for i in range(len(x)):
    for j in range(len(x[0])):
        total += x[i][j] * x[i][j] 
total

tensor(0.7874)

In [40]:
# Hadamard product (element wise multiplication)
x_hp = torch.einsum("ij,ij->ij", x, x)
x_hp

tensor([[1.8183e-05, 1.7253e-01, 2.3168e-01],
        [2.8110e-02, 1.1951e-01, 2.3553e-01]])

In [46]:
# outer product
a = torch.rand(3)
b = torch.rand(5)

In [47]:


x_op = torch.einsum("i,j->ij", a, b)
x_op

tensor([[0.0846, 0.1276, 0.1738, 0.1005, 0.3272],
        [0.0099, 0.0150, 0.0204, 0.0118, 0.0384],
        [0.1187, 0.1791, 0.2439, 0.1411, 0.4594]])

In [51]:
# cross roduct of 2 vectors
test = torch.empty((3, 5))
for i in range(len(a)):
    for j in range(len(b)):
        test[i,j] = a[i] * b[j] 
    
test


tensor([[0.0846, 0.1276, 0.1738, 0.1005, 0.3272],
        [0.0099, 0.0150, 0.0204, 0.0118, 0.0384],
        [0.1187, 0.1791, 0.2439, 0.1411, 0.4594]])

In [53]:
# Batch Matrix Mutiplication

a = torch.rand((3, 2, 5))
b = torch.rand((3, 5, 3))

x_bmm = torch.einsum("ijk,ikl->ijl", a, b)
x_bmm.shape

torch.Size([3, 2, 3])

In [55]:
# Matrix Diagonal
x = torch.rand(3,3)
print(x)
x_diag = torch.einsum("ii->i", x)
x_diag

tensor([[0.5594, 0.9447, 0.9372],
        [0.2321, 0.0884, 0.9172],
        [0.3127, 0.8367, 0.4913]])


tensor([0.5594, 0.0884, 0.4913])

In [56]:
# Matrix trace
x_trace = torch.einsum("ii->", x)
x_trace


tensor(1.1392)