## Tensor Operations

In [6]:
import torch

In [268]:
# get the device
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [271]:
# create a tensor
my_tensor = torch.tensor([[1,2], [3,4]], device=device)
my_tensor

tensor([[1, 2],
        [3, 4]])

In [272]:
# check where the tensor resides
my_tensor.device

device(type='cpu')

In [273]:
# tensor shape
my_tensor.shape

torch.Size([2, 2])

In [343]:
# no of dimensions
x.ndimension()

2

In [274]:
# no of elements in a tensor
tensor.numel()

9

In [275]:
# create a tensor of dim 2*3
torch.rand((2, 3))

tensor([[0.3019, 0.5937, 0.4377],
        [0.1261, 0.5982, 0.2558]])

In [276]:
# zero element tensor
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [292]:
# all-ones
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [278]:
# create a identity matrix
torch.eye(3,3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [293]:
# generate integers in a range
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [294]:
torch.arange(start=0, end=10, step=2)

tensor([0, 2, 4, 6, 8])

In [295]:
# generate equally spaced float values 
torch.linspace(start=0.1, end=1, steps=10)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

In [298]:
# check type of a tensor
tensor.dtype

torch.int64

In [299]:
# convert b/w datatypes
tensor.short()

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int16)

In [301]:
tensor.float()

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [302]:
tensor.double().dtype
tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [304]:
tensor.bool()
tensor

tensor([False,  True,  True,  True,  True,  True,  True,  True,  True,  True])

In [305]:
# convert between numpy and tensor
import numpy as np
np_array = np.random.normal(size=(3,3))
np_array

array([[-0.56108381, -1.30753265, -0.6620581 ],
       [ 0.45575169,  0.01014865, -0.30978659],
       [ 0.39143701, -0.52060504, -0.99407157]])

In [306]:
tensor = torch.from_numpy(np_array)
tensor

tensor([[-0.5611, -1.3075, -0.6621],
        [ 0.4558,  0.0101, -0.3098],
        [ 0.3914, -0.5206, -0.9941]], dtype=torch.float64)

In [307]:
np_array = tensor.numpy()
np_array

array([[-0.56108381, -1.30753265, -0.6620581 ],
       [ 0.45575169,  0.01014865, -0.30978659],
       [ 0.39143701, -0.52060504, -0.99407157]])

## Math Operations

In [309]:
# math operations
x = torch.tensor([1, 2, 3])
y = torch.tensor([9, 8, 7])

In [310]:
x + y

tensor([10, 10, 10])

In [311]:
x - y

tensor([-8, -6, -4])

In [312]:
x * y

tensor([ 9, 16, 21])

In [313]:
x = torch.rand((2,3))
y = torch.rand((3,2))

xy = x.mm(y)
xy

tensor([[0.3714, 0.4911],
        [0.5264, 0.4841]])

In [315]:
# batch matrix multiplication
b=10
m=2
n=3
p=3
q=4

x = torch.rand((b, m, n))
y = torch.rand((b, p, q))
x.bmm(y).shape

torch.Size([10, 2, 4])

In [316]:
x = torch.rand((2,3))
y = torch.rand((3,2))

In [317]:
x

tensor([[0.6750, 0.0764, 0.0151],
        [0.4787, 0.9619, 0.0352]])

In [326]:
# returns the min value and index. Dim is not required, in that case it will return min value in whole tensor
x.min(dim=0)

torch.return_types.min(
values=tensor([0.4787, 0.0764, 0.0151]),
indices=tensor([1, 0, 0]))

In [195]:
x

tensor([[2.3582e-02, 1.2050e-01, 2.4329e-01],
        [9.6208e-04, 1.2632e-01, 9.8064e-01]])

In [327]:
# returns the position of max value in the dimension
x.argmax(dim=1)

tensor([0, 1])

In [328]:
x.argmin(dim=1)

tensor([2, 2])

In [329]:
# sort values
sorted_x = x.sort(dim=1, descending=True)
sorted_x

torch.return_types.sort(
values=tensor([[0.6750, 0.0764, 0.0151],
        [0.9619, 0.4787, 0.0352]]),
indices=tensor([[0, 1, 2],
        [1, 0, 2]]))

In [330]:
# clamp to a min or max value
x = x.clamp(min=0.5)
x

tensor([[0.6750, 0.5000, 0.5000],
        [0.5000, 0.9619, 0.5000]])

In [331]:
# boolean operations
x = torch.tensor([1, 0, 1], dtype=torch.bool)
x

tensor([ True, False,  True])

In [332]:
x.any()

tensor(True)

In [333]:
x.all()

tensor(False)

## Indexing Operations

In [200]:
batch_size = 10
features = 25

x = torch.rand(batch_size, features)
x.shape

torch.Size([10, 25])

In [201]:
x[0].shape

torch.Size([25])

In [202]:
x[:, 0].shape

torch.Size([10])

In [204]:
# third example in batch first ten features
x[2, :10].shape

torch.Size([10])

In [89]:
x[0,0] = 100

In [205]:
x = torch.arange(10)
x[[0, 5, 9]]

tensor([0, 5, 9])

In [208]:
x = torch.rand((3, 5))
x

tensor([[0.0677, 0.6472, 0.5767, 0.9502, 0.4385],
        [0.0014, 0.7880, 0.5049, 0.7936, 0.8620],
        [0.5800, 0.6330, 0.3880, 0.7846, 0.7463]])

In [210]:
rows = torch.tensor([1, 0])
cols = torch.tensor([4, 0])
print(x[rows, cols])  # Gets second row fifth column and first row first column

tensor([0.8620, 0.0677])


In [337]:
x = torch.randint(0, 10, size=(3, 10))
x

tensor([[2, 6, 9, 9, 7, 2, 3, 7, 9, 6],
        [4, 9, 8, 9, 8, 7, 6, 3, 1, 1],
        [3, 0, 1, 2, 8, 7, 3, 9, 4, 7]])

In [338]:
x[(x<0) | (x>3)]

tensor([6, 9, 9, 7, 7, 9, 6, 4, 9, 8, 9, 8, 7, 6, 8, 7, 9, 4, 7])

In [346]:
torch.where(x>2)

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2]),
 tensor([1, 2, 3, 4, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 0, 4, 5, 6, 7, 8, 9]))

In [340]:
torch.where(x>2, x, x**2)

tensor([[4, 6, 9, 9, 7, 4, 3, 7, 9, 6],
        [4, 9, 8, 9, 8, 7, 6, 3, 1, 1],
        [3, 0, 1, 4, 8, 7, 3, 9, 4, 7]])

In [342]:
x.unique()

tensor([0, 1, 2, 3, 4, 6, 7, 8, 9])

## Reshaping

In [348]:
x = torch.arange(9)
print(x.shape)
x = x.view((3,3))
print(x.shape)

torch.Size([9])
torch.Size([3, 3])


In [349]:
x = torch.rand(3, 5)
y = torch.rand(3, 5)

In [350]:
x

tensor([[0.1679, 0.4608, 0.8626, 0.4603, 0.1959],
        [0.5858, 0.3256, 0.3940, 0.1120, 0.6246],
        [0.6380, 0.8769, 0.9303, 0.2529, 0.7316]])

In [351]:
torch.cat((x, y), dim=1).shape


torch.Size([3, 10])

In [352]:
torch.cat((x, y), dim=0).shape

torch.Size([6, 5])

In [353]:
x

tensor([[0.1679, 0.4608, 0.8626, 0.4603, 0.1959],
        [0.5858, 0.3256, 0.3940, 0.1120, 0.6246],
        [0.6380, 0.8769, 0.9303, 0.2529, 0.7316]])

In [354]:
x.view(-1).shape

torch.Size([15])

In [356]:
batch = 24
x = torch.rand(batch, 2, 5)
x.view(batch, -1).shape

torch.Size([24, 10])

In [357]:
x.shape

torch.Size([24, 2, 5])

In [358]:
# juggle with the dimensions
print(x.shape)
x.permute(1, 2, 0).shape

torch.Size([24, 2, 5])


torch.Size([2, 5, 24])

In [362]:
x = torch.arange(10)
x.shape

torch.Size([10])

In [363]:
# introduce an extra dimension in x axis
x = x.unsqueeze(dim=0)
x.shape

torch.Size([1, 10])

In [370]:
# introduce an extra dimension in y-axis
x = torch.arange(10)
x = x.unsqueeze(dim=1)
x.shape

torch.Size([10, 1])

In [371]:
# remove the extra dimension in y-axis
x = x.squeeze(dim=1)
x.shape

torch.Size([10])